# Generated by Django 4.1 on 2023-03-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100, null=True)),
                ("youtube_link", models.CharField(max_length=100, null=True)),
                ("music_link", models.CharField(max_length=100, null=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                (
                    "songs",
                    models.ManyToManyField(null=True, to="music_management.song"),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
